export default {
  pm: {
    wario: "Wario",
    mario: "Mario",
    luigi: "Luigi",
    peach: "Peach",
    bowser: "Bowser",
    yoshi: "Yoshi",
    dk: "Donkey Kong",
    diddy: "Diddy Kong",
    sonic: "Sonic",
    wolf: "Wolf",
    fox: "Fox",
    falco: "Falco",
    ic: "Ice Climbers",
    zelda: "Zelda",
    sheik: "Sheik",
    link: "Link",
    tlink: "Toon Link",
    ganon: "Ganondorf",
    mewtwo: "Mewtwo",
    lucario: "Lucario",
    pikachu: "Pikachu",
    puff: "Jigglypuff",
    squirtle: "Squirtle",
    ivy: "Ivysaur",
    charizard: "Charizard",
    samus: "Samus",
    zss: "Zero Suit Samus",
    lucas: "Lucas",
    ness: "Ness",
    pit: "Pit",
    kirby: "Kirby",
    metaknight: "Meta Knight",
    ddd: "Dedede",
    ike: "Ike",
    marth: "Marth",
    roy: "Roy",
    olimar: "Olimar",
    rob: "R.O.B.",
    gw: "Mr. Game & Watch",
    falcon: "Captain Falcon",
    snake: "Snake"
  },
  melee: {
    dmario: "Dr. Mario",
    mario: "Mario",
    luigi: "Luigi",
    bowser: "Bowser",
    peach: "Peach",
    yoshi: "Yoshi",
    dk: "Donkey Kong",
    falcon: "Captain Falcon",
    ganon: "Ganondorf",
    falco: "Falco",
    fox: "Fox",
    ness: "Ness",
    ic: "Ice Climbers",
    kirby: "Kirby",
    samus: "Samus",
    zelda: "Zelda",
    link: "Link",
    ylink: "Young Link",
    pichu: "Pichu",
    pikachu: "Pikachu",
    puff: "Jigglypuff",
    mewtwo: "Mewtwo",
    gw: "Mr. Game & Watch",
    marth: "Marth",
    roy: "Roy"
  }
};
